# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger: none
      
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'ids4admin:1.$(Build.BuildId)'
  
steps:
- script: |
    npm install bower
    cd src/IdentityServer4.Admin
    bower install
    cd ../..
    dotnet build --configuration $(buildConfiguration) 
    dotnet publish --configuration $(buildConfiguration) --output out
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    docker build -f Dockerfile -t $(dockerId)/ids4admin:latest .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
    docker push $(dockerId)/ids4admin:latest    
    
  env:
    pswd: $(dockerPassword)
